### ISSUE TITLE
yarn run dev

### ISSUE THREAD

**Issue by benlopes** [dominicarrojado/dominicarrojado.github.io#12]
I'm sorry if this is an unnecessary issue, but I couldn't find the solution on Google.

As I was following your tutorial, running "yarn run dev" didn't work well for me.

I got this result on the terminal:

**[1] /usr/bin/env: ‘node\r’: No such file or directory**
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn server exited with code 127
[0] Now watching file: me/Downloads/company/sample-email-template/src/index.mjml
[0] /me/Downloads/company/sample-email-template/src/index.mjml - Change detected
[0] /me/Downloads/company/sample-email-template/src/index.mjml - Successfully compiled

So the live-server function doesn't work and the index.html isn't opened on the browser.

**Comment by dominicarrojado** [comment]
@benlopes no worries at all, thanks for opening up an issue regarding this. You're right, the issue seems to be on `live-server` library, I just verified and the latest version is causing the issue, if you install the previous version `live-server@1.2.1`, this issue will not happen. I'll update the post/tutorial to install previous version in the meantime.

An issue has already been created for the `live-server` library here - https://github.com/tapio/live-server/issues/394
